language: node_js
node_js:
  - "10"
script:
  - npm run build
  - npm test
  - npm run coverage
before_install: npm install mocha chai supertest babel-cli babel-preset-env rimraf coveralls istanbul -g
after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info