language: node_js
env:
  - DATABASE_URL='postgres://postgres@localhost:5432/fast_food'
node_js:
  - "10"
services:
  - postgresql
addons:
  code_climate:
    repo_token:
      secure: 22c0a255f0cae72a9acf37099f905f5ef12653ada670e84f59699c224dc698f1
  postgresql: "9.6"
script:
  - npm test
  - npm run coverage
before_install: npm install mocha chai supertest babel-cli babel-preset-env codeclimate-test-reporter coveralls istanbul -g
after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
  - codeclimate-test-reporter < ./coverage/lcov.info
before_script:
  - psql -c 'create database fast_food;' -U postgres
  - export JWT_SECRET=4AF36685d35B8889A9d8801576B28b79C7AD8209